<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/concordium/health.proto

namespace Concordium\Health;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response to the health check. A return code of "OK" is used for success, and
 * errors are handled via RPC status codes
 *
 * Generated from protobuf message <code>concordium.health.NodeHealthResponse</code>
 */
class NodeHealthResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\Concordium\Health::initOnce();
        parent::__construct($data);
    }

}

