<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/concordium/health.proto

namespace Concordium\Health;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Parameters to the node health query. The default message gives a good
 * default.
 *
 * Generated from protobuf message <code>concordium.health.NodeHealthRequest</code>
 */
class NodeHealthRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\Concordium\Health::initOnce();
        parent::__construct($data);
    }

}

