<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium\NodeInfoResponse;

/**
 * Protobuf type <code>concordium.NodeInfoResponse.IsInBakingCommittee</code>
 */
class IsInBakingCommittee
{
    /**
     * The node is not the baking committee.
     *
     * Generated from protobuf enum <code>NOT_IN_COMMITTEE = 0;</code>
     */
    const NOT_IN_COMMITTEE = 0;
    /**
     * The node has baker keys, but the account is not currently a baker (and possibly never will be).
     *
     * Generated from protobuf enum <code>ADDED_BUT_NOT_ACTIVE_IN_COMMITTEE = 1;</code>
     */
    const ADDED_BUT_NOT_ACTIVE_IN_COMMITTEE = 1;
    /**
     * The node has baker keys, but they don't match the current keys on the baker account.
     *
     * Generated from protobuf enum <code>ADDED_BUT_WRONG_KEYS = 2;</code>
     */
    const ADDED_BUT_WRONG_KEYS = 2;
    /**
     * The node has valid baker keys and is active in the baker committee.
     *
     * Generated from protobuf enum <code>ACTIVE_IN_COMMITTEE = 3;</code>
     */
    const ACTIVE_IN_COMMITTEE = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IsInBakingCommittee::class, \Concordium\NodeInfoResponse_IsInBakingCommittee::class);

