<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for gettings the blocks at a specific height.
 *
 * Generated from protobuf message <code>concordium.BlockHeight</code>
 */
class BlockHeight extends \Google\Protobuf\Internal\Message
{
    /**
     * The block height.
     *
     * Generated from protobuf field <code>uint64 block_height = 1 [jstype = JS_STRING];</code>
     */
    private $block_height = 0;
    /**
     * The block height is relative to the genesis block at this index.
     *
     * Generated from protobuf field <code>uint32 from_genesis_index = 2;</code>
     */
    private $from_genesis_index = 0;
    /**
     * If true, only return results from the specified genesis index.
     *
     * Generated from protobuf field <code>bool restrict_to_genesis_index = 3;</code>
     */
    private $restrict_to_genesis_index = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $block_height
     *           The block height.
     *     @type int $from_genesis_index
     *           The block height is relative to the genesis block at this index.
     *     @type bool $restrict_to_genesis_index
     *           If true, only return results from the specified genesis index.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The block height.
     *
     * Generated from protobuf field <code>uint64 block_height = 1 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getBlockHeight()
    {
        return $this->block_height;
    }

    /**
     * The block height.
     *
     * Generated from protobuf field <code>uint64 block_height = 1 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockHeight($var)
    {
        GPBUtil::checkUint64($var);
        $this->block_height = $var;

        return $this;
    }

    /**
     * The block height is relative to the genesis block at this index.
     *
     * Generated from protobuf field <code>uint32 from_genesis_index = 2;</code>
     * @return int
     */
    public function getFromGenesisIndex()
    {
        return $this->from_genesis_index;
    }

    /**
     * The block height is relative to the genesis block at this index.
     *
     * Generated from protobuf field <code>uint32 from_genesis_index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFromGenesisIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->from_genesis_index = $var;

        return $this;
    }

    /**
     * If true, only return results from the specified genesis index.
     *
     * Generated from protobuf field <code>bool restrict_to_genesis_index = 3;</code>
     * @return bool
     */
    public function getRestrictToGenesisIndex()
    {
        return $this->restrict_to_genesis_index;
    }

    /**
     * If true, only return results from the specified genesis index.
     *
     * Generated from protobuf field <code>bool restrict_to_genesis_index = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setRestrictToGenesisIndex($var)
    {
        GPBUtil::checkBool($var);
        $this->restrict_to_genesis_index = $var;

        return $this;
    }

}

