<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to enable dumping of network packages.
 *
 * Generated from protobuf message <code>concordium.DumpRequest</code>
 */
class DumpRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Which file to dump the packages into.
     *
     * Generated from protobuf field <code>string file = 1;</code>
     */
    private $file = '';
    /**
     * Whether the node should dump raw packages.
     *
     * Generated from protobuf field <code>bool raw = 2;</code>
     */
    private $raw = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file
     *           Which file to dump the packages into.
     *     @type bool $raw
     *           Whether the node should dump raw packages.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Which file to dump the packages into.
     *
     * Generated from protobuf field <code>string file = 1;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Which file to dump the packages into.
     *
     * Generated from protobuf field <code>string file = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->file = $var;

        return $this;
    }

    /**
     * Whether the node should dump raw packages.
     *
     * Generated from protobuf field <code>bool raw = 2;</code>
     * @return bool
     */
    public function getRaw()
    {
        return $this->raw;
    }

    /**
     * Whether the node should dump raw packages.
     *
     * Generated from protobuf field <code>bool raw = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setRaw($var)
    {
        GPBUtil::checkBool($var);
        $this->raw = $var;

        return $this;
    }

}

