<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for getting the source of a smart contract module.
 *
 * Generated from protobuf message <code>concordium.GetModuleSourceRequest</code>
 */
class GetModuleSourceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The block to be used for the query.
     *
     * Generated from protobuf field <code>string block_hash = 1;</code>
     */
    private $block_hash = '';
    /**
     * The reference (hash) of the module.
     *
     * Generated from protobuf field <code>string module_ref = 2;</code>
     */
    private $module_ref = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $block_hash
     *           The block to be used for the query.
     *     @type string $module_ref
     *           The reference (hash) of the module.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The block to be used for the query.
     *
     * Generated from protobuf field <code>string block_hash = 1;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->block_hash;
    }

    /**
     * The block to be used for the query.
     *
     * Generated from protobuf field <code>string block_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->block_hash = $var;

        return $this;
    }

    /**
     * The reference (hash) of the module.
     *
     * Generated from protobuf field <code>string module_ref = 2;</code>
     * @return string
     */
    public function getModuleRef()
    {
        return $this->module_ref;
    }

    /**
     * The reference (hash) of the module.
     *
     * Generated from protobuf field <code>string module_ref = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModuleRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->module_ref = $var;

        return $this;
    }

}

