<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for getting the status of a transaction in a given block.
 *
 * Generated from protobuf message <code>concordium.GetTransactionStatusInBlockRequest</code>
 */
class GetTransactionStatusInBlockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The transaction hash.
     *
     * Generated from protobuf field <code>string transaction_hash = 1;</code>
     */
    private $transaction_hash = '';
    /**
     * The block hash.
     *
     * Generated from protobuf field <code>string block_hash = 2;</code>
     */
    private $block_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transaction_hash
     *           The transaction hash.
     *     @type string $block_hash
     *           The block hash.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The transaction hash.
     *
     * Generated from protobuf field <code>string transaction_hash = 1;</code>
     * @return string
     */
    public function getTransactionHash()
    {
        return $this->transaction_hash;
    }

    /**
     * The transaction hash.
     *
     * Generated from protobuf field <code>string transaction_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_hash = $var;

        return $this;
    }

    /**
     * The block hash.
     *
     * Generated from protobuf field <code>string block_hash = 2;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->block_hash;
    }

    /**
     * The block hash.
     *
     * Generated from protobuf field <code>string block_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->block_hash = $var;

        return $this;
    }

}

