<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for invoking a contract without a transaction.
 *
 * Generated from protobuf message <code>concordium.InvokeContractRequest</code>
 */
class InvokeContractRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Hash of the block (encoded in hex) at which to invoke the contract.
     *
     * Generated from protobuf field <code>string block_hash = 1;</code>
     */
    private $block_hash = '';
    /**
     * A JSON object that specifies which contract to invoke, and how.
     * A JSON schema for the context is provided at: https://developer.concordium.software/en/mainnet/net/references/grpc.html.
     *
     * Generated from protobuf field <code>string context = 2;</code>
     */
    private $context = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $block_hash
     *           Hash of the block (encoded in hex) at which to invoke the contract.
     *     @type string $context
     *           A JSON object that specifies which contract to invoke, and how.
     *           A JSON schema for the context is provided at: https://developer.concordium.software/en/mainnet/net/references/grpc.html.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Hash of the block (encoded in hex) at which to invoke the contract.
     *
     * Generated from protobuf field <code>string block_hash = 1;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->block_hash;
    }

    /**
     * Hash of the block (encoded in hex) at which to invoke the contract.
     *
     * Generated from protobuf field <code>string block_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->block_hash = $var;

        return $this;
    }

    /**
     * A JSON object that specifies which contract to invoke, and how.
     * A JSON schema for the context is provided at: https://developer.concordium.software/en/mainnet/net/references/grpc.html.
     *
     * Generated from protobuf field <code>string context = 2;</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * A JSON object that specifies which contract to invoke, and how.
     * A JSON schema for the context is provided at: https://developer.concordium.software/en/mainnet/net/references/grpc.html.
     *
     * Generated from protobuf field <code>string context = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkString($var, True);
        $this->context = $var;

        return $this;
    }

}

