<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A request to change the network.
 *
 * Generated from protobuf message <code>concordium.NetworkChangeRequest</code>
 */
class NetworkChangeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The identifier for the network.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value network_id = 1;</code>
     */
    private $network_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Int32Value $network_id
     *           The identifier for the network.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The identifier for the network.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value network_id = 1;</code>
     * @return \Google\Protobuf\Int32Value
     */
    public function getNetworkId()
    {
        return $this->network_id;
    }

    /**
     * The identifier for the network.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value network_id = 1;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setNetworkId($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->network_id = $var;

        return $this;
    }

}

