<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

if (false) {
    /**
     * This class is deprecated. Use Concordium\NodeInfoResponse\IsInBakingCommittee instead.
     * @deprecated
     */
    class NodeInfoResponse_IsInBakingCommittee {}
}
class_exists(NodeInfoResponse\IsInBakingCommittee::class);
@trigger_error('Concordium\NodeInfoResponse_IsInBakingCommittee is deprecated and will be removed in the next major release. Use Concordium\NodeInfoResponse\IsInBakingCommittee instead', E_USER_DEPRECATED);

