<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for getting (information about) the peers.
 *
 * Generated from protobuf message <code>concordium.PeersRequest</code>
 */
class PeersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Whether bootstrapper nodes should be included in the result.
     *
     * Generated from protobuf field <code>bool include_bootstrappers = 1;</code>
     */
    private $include_bootstrappers = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $include_bootstrappers
     *           Whether bootstrapper nodes should be included in the result.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Whether bootstrapper nodes should be included in the result.
     *
     * Generated from protobuf field <code>bool include_bootstrappers = 1;</code>
     * @return bool
     */
    public function getIncludeBootstrappers()
    {
        return $this->include_bootstrappers;
    }

    /**
     * Whether bootstrapper nodes should be included in the result.
     *
     * Generated from protobuf field <code>bool include_bootstrappers = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeBootstrappers($var)
    {
        GPBUtil::checkBool($var);
        $this->include_bootstrappers = $var;

        return $this;
    }

}

