<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

if (false) {
    /**
     * This class is deprecated. Use Concordium\PeerStatsResponse\PeerStats instead.
     * @deprecated
     */
    class PeerStatsResponse_PeerStats {}
}
class_exists(PeerStatsResponse\PeerStats::class);
@trigger_error('Concordium\PeerStatsResponse_PeerStats is deprecated and will be removed in the next major release. Use Concordium\PeerStatsResponse\PeerStats instead', E_USER_DEPRECATED);

