<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

if (false) {
    /**
     * This class is deprecated. Use Concordium\PeerElement\CatchupStatus instead.
     * @deprecated
     */
    class PeerElement_CatchupStatus {}
}
class_exists(PeerElement\CatchupStatus::class);
@trigger_error('Concordium\PeerElement_CatchupStatus is deprecated and will be removed in the next major release. Use Concordium\PeerElement\CatchupStatus instead', E_USER_DEPRECATED);

