<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A request that suggests the node to connect to the specified peer.
 *
 * Generated from protobuf message <code>concordium.PeerConnectRequest</code>
 */
class PeerConnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The IP of the peer.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue ip = 1;</code>
     */
    private $ip = null;
    /**
     * The port of the peer.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value port = 2;</code>
     */
    private $port = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $ip
     *           The IP of the peer.
     *     @type \Google\Protobuf\Int32Value $port
     *           The port of the peer.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The IP of the peer.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue ip = 1;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * The IP of the peer.
     *
     * Generated from protobuf field <code>.google.protobuf.StringValue ip = 1;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->ip = $var;

        return $this;
    }

    /**
     * The port of the peer.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value port = 2;</code>
     * @return \Google\Protobuf\Int32Value
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * The port of the peer.
     *
     * Generated from protobuf field <code>.google.protobuf.Int32Value port = 2;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->port = $var;

        return $this;
    }

}

