<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A response containing information about a peer.
 *
 * Generated from protobuf message <code>concordium.PeerStatsResponse</code>
 */
class PeerStatsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of stats for the peers.
     *
     * Generated from protobuf field <code>repeated .concordium.PeerStatsResponse.PeerStats peerstats = 1;</code>
     */
    private $peerstats;
    /**
     * Average outbound throughput in bytes per second.
     *
     * Generated from protobuf field <code>uint64 avg_bps_in = 2 [jstype = JS_STRING];</code>
     */
    private $avg_bps_in = 0;
    /**
     * Average inbound throughput in bytes per second.
     *
     * Generated from protobuf field <code>uint64 avg_bps_out = 3 [jstype = JS_STRING];</code>
     */
    private $avg_bps_out = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Concordium\PeerStatsResponse\PeerStats[]|\Google\Protobuf\Internal\RepeatedField $peerstats
     *           A list of stats for the peers.
     *     @type int|string $avg_bps_in
     *           Average outbound throughput in bytes per second.
     *     @type int|string $avg_bps_out
     *           Average inbound throughput in bytes per second.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of stats for the peers.
     *
     * Generated from protobuf field <code>repeated .concordium.PeerStatsResponse.PeerStats peerstats = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeerstats()
    {
        return $this->peerstats;
    }

    /**
     * A list of stats for the peers.
     *
     * Generated from protobuf field <code>repeated .concordium.PeerStatsResponse.PeerStats peerstats = 1;</code>
     * @param \Concordium\PeerStatsResponse\PeerStats[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeerstats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Concordium\PeerStatsResponse\PeerStats::class);
        $this->peerstats = $arr;

        return $this;
    }

    /**
     * Average outbound throughput in bytes per second.
     *
     * Generated from protobuf field <code>uint64 avg_bps_in = 2 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getAvgBpsIn()
    {
        return $this->avg_bps_in;
    }

    /**
     * Average outbound throughput in bytes per second.
     *
     * Generated from protobuf field <code>uint64 avg_bps_in = 2 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAvgBpsIn($var)
    {
        GPBUtil::checkUint64($var);
        $this->avg_bps_in = $var;

        return $this;
    }

    /**
     * Average inbound throughput in bytes per second.
     *
     * Generated from protobuf field <code>uint64 avg_bps_out = 3 [jstype = JS_STRING];</code>
     * @return int|string
     */
    public function getAvgBpsOut()
    {
        return $this->avg_bps_out;
    }

    /**
     * Average inbound throughput in bytes per second.
     *
     * Generated from protobuf field <code>uint64 avg_bps_out = 3 [jstype = JS_STRING];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAvgBpsOut($var)
    {
        GPBUtil::checkUint64($var);
        $this->avg_bps_out = $var;

        return $this;
    }

}

