<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concordium_p2p_rpc.proto

namespace Concordium;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A response containing a list of peers.
 *
 * Generated from protobuf message <code>concordium.PeerListResponse</code>
 */
class PeerListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of the queried node.
     * Possible values: "Node" or "Bootstrapper".
     *
     * Generated from protobuf field <code>string peer_type = 1;</code>
     */
    private $peer_type = '';
    /**
     * A list of peers.
     *
     * Generated from protobuf field <code>repeated .concordium.PeerElement peers = 2;</code>
     */
    private $peers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $peer_type
     *           The type of the queried node.
     *           Possible values: "Node" or "Bootstrapper".
     *     @type \Concordium\PeerElement[]|\Google\Protobuf\Internal\RepeatedField $peers
     *           A list of peers.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConcordiumP2PRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of the queried node.
     * Possible values: "Node" or "Bootstrapper".
     *
     * Generated from protobuf field <code>string peer_type = 1;</code>
     * @return string
     */
    public function getPeerType()
    {
        return $this->peer_type;
    }

    /**
     * The type of the queried node.
     * Possible values: "Node" or "Bootstrapper".
     *
     * Generated from protobuf field <code>string peer_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerType($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer_type = $var;

        return $this;
    }

    /**
     * A list of peers.
     *
     * Generated from protobuf field <code>repeated .concordium.PeerElement peers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeers()
    {
        return $this->peers;
    }

    /**
     * A list of peers.
     *
     * Generated from protobuf field <code>repeated .concordium.PeerElement peers = 2;</code>
     * @param \Concordium\PeerElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Concordium\PeerElement::class);
        $this->peers = $arr;

        return $this;
    }

}

